//
// Created by idanto on 01/01/2020.
//

#ifndef BOOST_ECHO_CLIENT_STOMPBOOKCLUBCLIENT_H
#define BOOST_ECHO_CLIENT_STOMPBOOKCLUBCLIENT_H


class StompBookClubClient {

};


#endif //BOOST_ECHO_CLIENT_STOMPBOOKCLUBCLIENT_H
